# Generated by Django 3.1.1 on 2020-10-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='image',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
